# Generated by Django 4.2 on 2023-06-17 09:01

from django.db import migrations, models
import validate


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(error_messages={'error': 'You dont enter name '}, help_text='You must enter your first name', max_length=300)),
                ('last_name', models.CharField(error_messages={'error': 'You dont enter name '}, help_text='You must enter your first name', max_length=300)),
                ('date_of_brith', models.CharField(help_text='Please input your brith "2000/01/01" format ', max_length=100)),
                ('gander', models.CharField(choices=[('M', 'Male'), ('Female', 'F'), ('N', 'Not interesting')])),
                ('passport', models.CharField(error_messages={'error': 'Your  passport must be start "AD"'}, help_text='Please enter Passport example "AD1234578" ', max_length=9, validators=[validate.Passport_validate])),
                ('phone', models.CharField(error_messages={'error': 'You dont input phone'}, help_text='Please input your phone', max_length=100)),
                ('email', models.EmailField(error_messages={'error': 'You dont input email'}, help_text='Please input your email', max_length=100)),
                ('contact', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
