# Generated by Django 4.2 on 2023-06-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuyTicket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyticket',
            name='contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='buyticket',
            name='gander',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Not interesting')]),
        ),
    ]
