# Generated by Django 4.2 on 2023-06-17 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuyTicket', '0002_alter_buyticket_contact_alter_buyticket_gander'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyticket',
            name='contact',
        ),
    ]
