# Generated by Django 4.2 on 2023-06-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuyTicket', '0006_buyticket_pay_fileds'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyticket',
            name='fly_ball',
            field=models.CharField(default=12),
            preserve_default=False,
        ),
    ]
