# Generated by Django 4.2 on 2023-06-18 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ticket', '0014_alter_ticket_tiket_number'),
        ('Discount', '0002_delete_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.CharField(max_length=100)),
                ('old_price', models.CharField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_tickets', to='Ticket.ticket')),
            ],
        ),
    ]
