# Generated by Django 4.2 on 2023-06-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discount', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='discount_price',
            field=models.CharField(default=12),
            preserve_default=False,
        ),
    ]
