# Generated by Django 4.2 on 2023-06-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_ball',
            field=models.CharField(default=0, help_text='You collect ball next you change your ball to someone our  items', null=True),
        ),
    ]
