# Generated by Django 4.2 on 2023-06-25 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_userball'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBall',
        ),
    ]
