# Generated by Django 4.2 on 2023-06-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_userball_ticket_alter_userball_ball'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userball',
            name='ball',
            field=models.CharField(max_length=1000),
        ),
    ]
