# Generated by Django 4.2 on 2023-06-25 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_alter_userball_ball'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_ball',
        ),
    ]
