# Generated by Django 4.2 on 2023-06-26 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BuyTicket', '0007_buyticket_fly_ball'),
        ('User', '0011_remove_user_user_ball'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balls',
            field=models.CharField(default=1, max_length=125656),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userball',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ball_sum', to='BuyTicket.buyticket'),
        ),
        migrations.AlterField(
            model_name='userball',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_s', to=settings.AUTH_USER_MODEL),
        ),
    ]
