# Generated by Django 4.2 on 2023-06-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticket_from', models.CharField(max_length=1000)),
                ('Ticket_to', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('tiket_number', models.CharField(default=983690)),
                ('bugges', models.SmallIntegerField(default=20)),
                ('hand_bugges', models.SmallIntegerField(default=8)),
                ('ball', models.CharField(default=5, max_length=1000)),
                ('class_tiket', models.CharField(choices=[('Business', 'bus'), ('Economy pro', 'eco pro'), ('Economy small', ' eco small'), ('Economy', ' eco')])),
            ],
        ),
    ]
