# Generated by Django 4.2 on 2023-06-17 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0002_alter_ticket_tiket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 6, 17, 8, 24, 15, 960674)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tiket_number',
            field=models.CharField(default=552483),
        ),
    ]
