# Generated by Django 4.2 on 2023-06-17 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0004_alter_ticket_tiket_number_alter_ticket_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tiket_number',
            field=models.CharField(default=839118),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 6, 17, 9, 1, 18, 859494, tzinfo=datetime.timezone.utc)),
        ),
    ]
