# Generated by Django 4.2 on 2023-06-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0012_alter_ticket_tiket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_price',
            field=models.CharField(default=45000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tiket_number',
            field=models.CharField(default=637073),
        ),
    ]
